# Generated by Django 4.2.1 on 2023-05-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_connect', models.DateField(auto_created=True, blank=True, help_text='Первое подключение робота', null=True, verbose_name='Первое подключение робота')),
                ('ipaddr', models.CharField(help_text='IP-адрес устройства', max_length=16, verbose_name='IP-адресс устройства')),
                ('token', models.CharField(blank=True, help_text='Кодовое наименование устройства', max_length=16, null=True, verbose_name='Кодовое наименование устройства')),
                ('is_connected', models.BooleanField(blank=True, help_text='Подключен ли робот?', null=True, verbose_name='Подключен ли робот')),
            ],
            options={
                'verbose_name': 'Робот',
                'verbose_name_plural': 'Роботы',
            },
        ),
    ]
