# Generated by Django 4.2.1 on 2023-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_robot_is_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='ipaddr',
            field=models.CharField(help_text='IP-адрес устройства', max_length=16, verbose_name='IP-адрес устройства'),
        ),
    ]
