# Generated by Django 4.2.1 on 2023-05-21 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='battery_num',
            field=models.IntegerField(blank=True, help_text='Остаток заряда аккумулятора', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Остаток заряда аккумулятора'),
        ),
    ]
