# Generated by Django 4.2.1 on 2023-05-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='date_sensor',
            field=models.DateTimeField(auto_created=True, blank=True, help_text='Дата и время снятия показания', null=True, verbose_name='Дата и время снятия показания'),
        ),
    ]
